#How to install docker CE in RHEL8
#https://linuxconfig.org/how-to-install-docker-in-rhel-8
#Solves issue of containerd.io > 1.2.0-3.el7 dependency
---
- block:
  - name: Wait for instances to be reachable
    wait_for_connection:
      sleep: 5
      timeout: 120

  - name: Install subscription-manager
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - subscription-manager
      - subscription-manager-migration
      - subscription-manager-migration-data
    become: yes

  - name: Register with activationkey and consume subscriptions matching Red Hat Enterprise Linux Server
    redhat_subscription:
      state: present
      activationkey: "{{ rhactivationkey }}"
      org_id: "{{ rhorg_id }}"
      auto_attach: true
    become: yes
  when: labels.cloud_provider == "gcp"
